### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [royranger/Jammming#4]
Code structure was great! Consistent with whitespace and indentations. Confident that even with the large amount of code and components, would be easy to read and search through with future expansion.

Many of the "issues" would just be refactoring code to make it cleaner and more space efficient but it's not a significant issue.

Project looks and is written really well. Personally thankful for your cleanliness and consistency with writing the code.

Superb job and keep up the good work!

Grade: Meets expectation.

**Comment by royranger** [comment]
Thanks very much!!
